### ISSUE TITLE
need ingredients

### ISSUE THREAD

**Issue by ag-dubs** [ag-dubs/peanutbutter-and-jelly-sandwich#1]
- bread
- peanut butter
- jelly

**Comment by ashleygwilliams** [comment]
hi! i'm happy to try to take this on! do you have any preferences?

**Comment by ag-dubs** [comment]
thanks @ashleygwilliams -- wheat bread for sure. not super opinionated on the others atm.

**Comment by joelhooks** [comment]
+1
